
/*
	► INSERT: SidtefimModulo */
INSERT INTO SidtefimModulo
	VALUES
	(
		'SITRAN', 1, 'Sistema de Trazabilidad de Nacionalización', 'Sistema de Trazabilidad de Nacionalización', '1.0'
	)


/*
	► INSERT: SidtefimProcedimiento
	► SELECT * FROM SidtefimProcedimiento */
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'AddBox','PARA EVALUACIÓN','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'Check','EN PROYECTO EVALUACIÓN','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'Clear','NO LEIDOS','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'DeleteOutline','REGISTRAR PROCEDIMIENTO','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'ChevronRight','PARA ASIGNAR','/test','SITRAN')
INSERT INTO SidtefimProcedimiento(bActivo, sIcono, sNombre, sRuta, sIdModulo) VALUES(1,'Edit','CONSULTAS','/test','SITRAN')

/*
	► INSERT: SidtefimDocumento
	► SELECT * FROM SidtefimDocumento */
INSERT INTO SidtefimDocumento(sDescripcion, bActivo) VALUES('MEMORANDUM',1)
INSERT INTO SidtefimDocumento(sDescripcion, bActivo) VALUES('OFICION',1)
INSERT INTO SidtefimDocumento(sDescripcion, bActivo) VALUES('CARTA',1)

/*
	► INSERT: SidtefimPais
	► SELECT * FROM SidtefimPais */
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('AFG',1,'AFGANA','AFGHANISTAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('AGI',1,'','AGUAS INTERNACIONALE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('AHO',1,'MELENSE','ANTILLAS HOLANDESAS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ALB',1,'ALBANESA','ALBANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ALE',0,'ALEMANA','ALEMANIA2')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ALG',0,'ALGERIANA','ALGERIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('AND',1,'ANDORRANA','ANDORRA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ANG',1,'ANGOLEÑA','ANGOLA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ANT',1,'ANTIGUA Y BARBUDA','ANT.BARBUDA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('APA',1,'APATRIADO','APATRIDA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ARL',1,'ARGELINA','ARGELIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ARM',1,'ARMENIA','ARMENIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ARN',1,'ARGENTINA','ARGENTINA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ARU',1,'ARUBA','ARUBA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ASA',1,'ARABE Y SAUDITA','ARABIA SAUDITA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('AUL',1,'AUSTRALIANA','AUSTRALIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('AUR',1,'AUSTRIACA','AUSTRIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('AVO',0,'ALTO VOLTA','ALTO VOLTA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('AZR',1,'AZERBAIYANO','AZERBAIYAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BAH',1,'BAHREIN','BAHREIN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BAN',1,'BANGLADESH','BANGLADESH')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BAR',1,'BARBADENSE','BARBADOS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BEL',1,'BELGA','BELGICA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BEN',1,'BENINES','BENIN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BER',1,'BERMUDAS','BERMUDAS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BHM',1,'BAHAMAS','BAHAMAS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BIR',0,'BIRMANA','BIRMANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BLC',1,'BELICEÑO','BELICE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BLG',0,'BELARUSO','BELARUS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BLR',1,'BIELORRUSA','BIELORRUSIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BOL',1,'BOLIVIANA','BOLIVIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BOS',1,'BOSNIA Y HERSEGOVINA','BOSNIA Y HERZEGOVINA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BOT',1,'BOSTWANES','BOTSWANA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BRA',1,'BRASILERA','BRASIL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BRK',1,'BURKINA FASO','BURKINA FASO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BRU',1,'BRUNEI DARUSSALAM','BRUNEI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BUL',1,'BULGARA','BULGARIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BUR',1,'BURUNDIANO','BURUNDI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('BUT',1,'BUTHANES','BHUTAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CAN',1,'CANADIENSE','CANADA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CEY',0,'CEYLANDES','CEYLAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CHA',1,'CHADIANO','CHAD')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CHE',1,'CHECA','REP.CHECA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CHL',1,'CHILENA','CHILE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CHN',1,'CHINA','CHINA (R.P)')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CHP',1,'CHIPRIOTA','CHIPRE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CMA',1,'COSTA DE MARFIL','COSTA MARFIL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CMB',1,'CAMBOYANO','CAMBOYA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CMR',1,'CAMERUNEZ','CAMERUN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CNO',1,'COREANA','COREA DEL NORTE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('COL',1,'COLOMBIANA','COLOMBIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('COM',1,'COMORANO','COMORAS (ISL)')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CON',1,'CONGOLEÑO','CONGO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('COT',0,'COTE DIVOIRE','COTE DIVOIRE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CRI',1,'COSTARRICENSE','COSTA RICA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CRO',1,'CROATA','CROACIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CSU',1,'COREANA','COREA DEL SUR')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CUB',1,'CUBANA','CUBA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CUR',1,'CURAZALEÑO','CURAZAO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('CVE',1,'CABOVERDIANA','CABO VERDE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('DIN',1,'DANESA','DINAMARCA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('DJI',1,'DJIBOUTI','DJIBOUTI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('DOM',1,'DOMINICA','DOMINICA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('EAU',1,'EMIRATOS ARABES UNIDOS','EMIRATOS ARABES UNID')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ECU',1,'ECUATORIANA','ECUADOR')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('EGI',1,'EGIPCIA','EGIPTO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ERI',1,'ERITREO','ERITREA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ESC',1,'ESCOCESA','ESCOCIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ESL',1,'ESLOVENO','ESLOVENIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ESP',1,'ESPAÑOLA','ESPAÑA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('EST',1,'ESTONIO','ESTONIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ESV',1,'ESLOVACA','ESLOVAQUIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ETI',1,'ETIOPE','ETIOPIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('FIJ',1,'DE FIJI','FIJI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('FIL',1,'FILIPINA','FILIPINAS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('FIN',1,'FINLANDESA','FINLANDIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('FRA',1,'FRANCESA','FRANCIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GAB',1,'GABONES','GABON')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GAM',1,'GAMBIANO','GAMBIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GBI',1,'GUINEANO','GUINEA BISSAU')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GEC',1,'GUINEANO','GUINEA ECUATORIAL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GEO',1,'GEORGIANO','GEORGIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GHA',1,'GHANES','GHANA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GRA',1,'GRANADINO','GRANADA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GRB',1,'BRITANICA','GRAN BRETAÑA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GRE',1,'GRIEGA','GRECIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GRO',1,'GROELANDESA','GROENLANDIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GUA',1,'GUATEMALTECA','GUATEMALA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GUF',1,'GUYANES','GUYANA FRANCESA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GUN',1,'GUINEANO','GUINEA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('GUY',1,'GUYANES','GUYANA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('HAI',1,'HAITIANO','HAITI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('HNK',1,'DE HONG KONG','HONG KONG')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('HOL',1,'HOLANDESA','HOLANDA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('HON',1,'HONDUREÑA','HONDURAS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('HUN',1,'HUNGARA','HUNGRIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('IDI',1,'INDIA','INDIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('IDO',1,'INDONESIO','INDONESIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ING',1,'INGLESA','INGLATERRA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('IRK',1,'IRAKI','IRAQ')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('IRL',1,'IRLANDESA','IRLANDA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('IRN',1,'IRANI','IRAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ISA',1,'ISLAS SALOMON','SALOMON ISLA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ISL',1,'ISLANDESA','ISLANDIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ISM',1,'ISLAND MARSHALL','ISLAND MARSHALL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ISR',1,'ISRAELI','ISRAEL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ITA',1,'ITALIANA','ITALIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('JAM',1,'JAMAIQUINA','JAMAICA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('JAP',1,'JAPONESA','JAPON')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('JOR',1,'JORDANO','JORDANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('KAZ',1,'KAZAKSTANI','KAZAJSTAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('KEN',1,'KENIANO','KENIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('KIR',1,'KIRIBATIANO','KIRIBATI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('KOS',1,'KOSOVO','KOSOVO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('KRG',1,'KIRGUIS','KIRGUISTAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('KUW',1,'KUWAITI','KUWAIT')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LAO',1,'DE LAOS','LAOS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LBA',1,'LIBANES','LIBANO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LBE',1,'LIBERIANA','LIBERIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LBI',1,'DE LIBIA','LIBIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LES',1,'DE LESOTHO','LESOTHO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LET',1,'LETON','LETONIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LIE',1,'DE LIECHTENSTEIN','LIECHTENSTEIN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LIT',1,'LITUANO','LITUANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LTV',0,'','LATVIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('LUX',1,'LUXENBURGUES','LUXEMBURGO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MAC',1,'MACEDONIA','EX R.YUG.MACEDONIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MAD',1,'MALGACHE','MADAGASCAR')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MAL',1,'MALDIVO','MALDIVAS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MAR',1,'MARROQUI','MARRUECOS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MAT',1,'MAURITANO','MAURITANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MAU',1,'MAURICIANO','MAURICIO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MCU',1,'','MACAO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MEX',1,'MEXICANA','MEXICO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MIC',1,'MICRONESIA','MICRONESIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MLB',1,'MALASIO','MALASIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MLD',1,'MOLDAVA','MOLDAVIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MLI',1,'MALIENSE','MALI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MLT',1,'MALTES','MALTA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MLW',1,'MALAWIANO','MALAWI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MNC',1,'MONEGASCO','MONACO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MNE',1,'MONTENEGRINO','MONTENEGRO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MNG',1,'MONGOL','MONGOLIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MOL',1,'MOLDOVO','REP.MOLDOVA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MOR',0,'MOROCCOS','MOROCCO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MOZ',1,'MOZAMBIQUEÑO','MOZAMBIQUE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('MYA',1,'DE MYANMAR','MYANMAR')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NAM',1,'NAMIBIANO','NAMIBIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NAU',1,'NAURUANO','NAURU')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NEP',1,'NEPALES','NEPAL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NGR',1,'NIGERIANO','NIGER')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NIA',1,'NIGERIANA','NIGERIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NIC',1,'NICARAGUENSE','NICARAGUA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NNN',1,'','<NO DEFINIDO>')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NOR',1,'NORUEGA','NORUEGA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('NZE',1,'NEOZELANDES','NUEVA ZELANDIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('OMA',1,'OMANI','OMAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PAK',1,'PAKISTANI','PAKISTAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PAL',1,'PALESTINA','PALESTINA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PAN',1,'PANAMEÑA','PANAMA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PAP',1,'DE PAPUA NUEVA GUINEA','PAPUA (NG)')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PAR',1,'PARAGUAYA','PARAGUAY')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PBA',1,'NEERLANDESA','PAISES BAJOS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PER',1,'PERUANA','PERU')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PLW',1,'PALAO','PALAOS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('POL',1,'POLACA','POLONIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('POR',1,'PORTUGUESA','PORTUGAL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PRI',1,'PUERTORIQUEÑA','PTO.RICO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('PYF',1,'FRANCOPOLINESIO','POLINESIA FRANCESA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('QAT',1,'DE KATAR','QATAR')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('RCE',1,'CENTRAFRICANO','REP.CENTROAFRI')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('RDA',0,'ALEMANA','ALEMANIA DEM')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('RDC',1,'CONGOLESA','REPUBLICA DEMOCRATICA DEL CONGO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('RDO',1,'DOMINICANA','REP. DOMINICANA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('RFA',1,'ALEMANA','ALEMANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ROD',0,'','RODHESIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('RUM',1,'RUMANA','RUMANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('RUS',1,'RUSA','RUSIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('RWA',1,'RWANDES','RWANDA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SAF',1,'SUDAFRICANA','SUDAFRICA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SAL',1,'SALVADOREÑA','EL SALVADOR')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SAM',1,'SAMOANO','SAMOA OCCIDENTAL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SCN',1,'SANCRISTOBALEÑA','SAN CRISTOBAL Y NIEVES')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SEN',1,'SENEGALES','SENEGAL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SEY',1,'DE SEYCHELLES','SEYCHELLES')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SIK',0,'','SIKKIM')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SIN',1,'DE SINGAPUR','SINGAPUR')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SIR',1,'SIRIO','SIRIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SKN',0,'ST CHRISTOPHER','SAINT KITIS Y NEVIS')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SLE',1,'SIERRALEONES','SIERRA LEONA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SLU',1,'SANTALUCENSE','SANTA LUCIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SMR',1,'DE SAN MARINO','SAN MARINO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SOM',1,'SOMALI','SOMALIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SRB',1,'SERBIO','SERBIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SRI',1,'DE SRI LANKA','SRI LANKA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('STP',1,'DE STO TOME Y PRINCIPE','STO.TOME Y PRINCIPE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SUD',1,'SUDANES','SUDAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SUE',1,'SUECA','SUECIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SUI',1,'SUIZA','SUIZA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SUR',1,'SURINAMES','SURINAM')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SVG',1,'SAN VICENTINO','SAN VIC.GRANA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SWA',1,'SWAZI','SWAZILANDIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('SYM',0,'SERBIO','SERBIA Y MONTENEGRO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TAY',1,'TAYIK','TAYIKISTAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TAZ',1,'TANZANO','TANZANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TLD',1,'TAILANDES','TAILANDIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TLS',1,'TIMORENSE','TIMOR ORIENTAL')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TOG',1,'TOGOLES','TOGO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TON',1,'TONGANO','TONGA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TRI',1,'DE TRINIDAD Y TOBAGO','TRINI.TOBAG')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TRK',1,'TURCOMANO','TURKMENISTAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TUN',1,'TUNESINO','TUNEZ')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TUR',1,'TURCA','TURQUIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TUV',1,'DE TUVALU','TUVALU')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('TWN',1,'CHINOS DE TAIWAN','TAIWAN (CHN)')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('UCR',1,'UCRANIANA','UCRANIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('UGA',1,'UGANDES','UGANDA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('URU',1,'URUGUAYA','URUGUAY')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('USA',1,'ESTADOUNIDENSE','EE.UU')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('UZB',1,'UZBEKO','UZBEKISTAN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('VAN',1,'DE VANUATU','VANUATU')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('VAT',1,'DE VATICANO','VATICANO')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('VEN',1,'VENEZOLANA','VENEZUELA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('VIE',1,'VIETNAMITA','VIETNAM')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('YRA',1,'DE YEMEN','YEMEN')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('YUG',0,'YUGOSLAVO','R.F.YUGOSLAVIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ZAI',0,'ZAIRENSE','ZAIRE')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ZAM',1,'ZAMBIANO','ZAMBIA')
INSERT INTO SidtefimPais(sIdPais, bActivo, sNacionalidad, sNombre) VALUES('ZIM',1,'ZIMBABWENSE','ZIMBABWE')

/*
	► INSERT: SidtefimDocumento
	► SELECT * FROM SidtefimTipoSolicitud */

INSERT INTO SidtefimTipoSolicitud VALUES('NAC',1,'Nacionalización')

/*
	► INSERT: SidtefimTipoTramite
	► SELECT * FROM SidtefimTipoTramite */
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'<NO DEFINIDO>','NNN','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'EXPEDICION DE PASAPORTE','EXP','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'REVALIDACION DE PASAPORTE','RVP','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ANULACION DE PASAPORTE','ANP','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PASAPORTE COLECTIVO','PCO','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ANULACION TRAMITE PASAPORTE','ATP','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ANULACION DE MOVIMIENTO MIGRATORIO','AMM','M')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'RECTIFICACION DE  MOVIMIENTO MIGRATORIO','RMM','M')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'TRAMITE ASOCIACION','APA','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'TRAMITE DESASOCIACION','DPA','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(0,'RECHAZO PASAPORTE','RPA','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(0,'RETENCION DE EXPEDIENTE','RET','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(0,'RECHAZO PASAPORTE CONTROL','RPC','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CANCELAR IMPRESION DE PASAPORTE','CIP','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'OFICIO MOVIMIENTO MIGRATORIO','OMM','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'INFORME MOVIMIENTO MIGRATORIO','IMM','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CERTIFICADO MOVIMIENTO MIGRATORIO','CMM','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CERTIFICADO DE PASAPORTE','CDP','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CERTIFICADO INSCRIPC. REGISTRO CENTRAL EXTRANJERÍA','CRE','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'COPIAS CERTIFICADAS DOCUMENTOS ORIG. CONTEN. EXPE.','LCE','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'FACILIDADES PERICIAS POLICIALES','FPP','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'OFICIOS CERTIFICANDO RESIDENCIA','OCR','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'COPIA AUTENTICADA DE DOCUMENTOS SUSTENTATORIOS DE','DSP','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'INFORME DE TITULARIDAD DE PASAPORTE','ITP','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'REMISION DE CUADROS NUMÉRICOS EXP Y REV DE PPTE','CNP','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'REMISON DE SALVOCONDUCTOS CONSULARES PCM Y CONSULA','RSC','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'VERIFICACION DE AUTENTICIDAD DE PPTE','VAP','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'IMPRESIONES DACTILARES, GENERALES DE LEY','GDL','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'OTROS','OTR','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'VERIFICACION DE DATOS','VRF','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CAMBIO DE CONSULADO - VISA','COV','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'EXONERACIÓN PAGO - PRORROGA RE','EXR','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PAGO TASA ANUAL EXTRANJERÍA','PAG','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'MODIFICACION DATOS RCE','MRC','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PERMISO DE VIAJE','PEV','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'SALIDAS CONCLUIDAS TEMPORALES','SAL','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CERTIFICADO DE VISA','CER','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ORDEN DE SALIDA Y REGISTRO EXPULSADOS','OSR','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CANC. PERMANENCIA/RESIDENCIA X OFICIO','CPR','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(0,'Solicitud de Visa MRE','SOM','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'SOLICITUD DE VISA','SOL','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PRORROGA DE PERMANENCIA','PRP','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PRORROGA DE RESIDENCIA','PRR','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CAMBIO DE CALIDAD MIGRATORIA','CCM','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CAMBIO DE CLASE DE VISA','CCV','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PERMISO PARA TRABAJAR','PET','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PERMISO ESP. FIRMAR CONTRATOS','PEF','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'INSCR.REG.CENTRAL EXTRANJERÍA','INS','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'DUPLICADO DE CE','DUP','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'EXONERACIÓN PAGO TASA ANUAL','EXT','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CANCE.RESIDENCIA Y SALIDA DEF.','CAN','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'TRASLADO DE SELLOS PARA RESIDENTES E INMIGRANTES','TRA','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CANCELACIÓN TRÁMITE','CTR','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'INS HIJOS DE PERUANOS NAC. EN EXT. MENORES DE EDAD','IME','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'COPIA CERTIFICADA DE CARNE DE EXTRANJERIA','CCE','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'INS HIJOS DE PERUANOS NAC. EN EXT. MAYORES DE EDAD','IMA','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'INS HIJOS DE EXT. NAC.EN EXT.RES PERÚ DESDE 5 AÑOS','IER','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'INS PERUANO POR MATRIMONIO','IPM','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'COPIA CERTIFICADA DE REGISTRO DE INSCRIPCIÓN','CCT','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'DUPLICADO DE REGISTRO DE INSCRIPCIÓN','DRI','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'OBTENCIÓN NACIONALIDAD PERUANA POR NATURALIZACIÓN','ONN','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ACTUALIZACIÓN DE DATOS EN REGISTROS DE INSCRIPCIÓN','ADR','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'OBTENCIÓN DE LA DOBLE NACIONALIDAD','ODN','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'RECUPERACIÓN DE LA NACIONALIDAD PERUANA','RNP','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(0,'DUPLICADO DE TÍTULO DE NACIONALIDAD','DTN','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'COPIA DE RESOLUCION','CRS','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'COPIA DE OFICIO','CPO','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CONSTANCIA DE SALIDA DEFINITIVA','CSD','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CONSTANCIA DE RESIDENCIA','CDR','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'REINTEGRO TRAMITE PASAPORTE','REP','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'RENUNCIA A LA NACIONALIDAD PERUANA','RNA','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(0,'ACTUALIZACIÓN DE DATOS EN TÍTULOS DE NACIONALIDAD','ATN','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(0,'COPIA CERTIFICADA DE TITULOS DE NACIONALIDAD','CTN','T')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PER.ESP.PER.FUER.D.PAÍS MÁS.D.183 DÍAS SIN PER.RES','PFP','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'Expedición de Pasaporte Electrónico','EPE','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ANULACIÓN TRAMITE PASAPORTE ELECTRÓNICO','APE','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'Permiso Temporal de Permanencia - Venezolanos','PTV','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'Permiso Temporal de Permanencia - Padres','PTE','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'CANC. PERMANENCIA/RESIDENCIA X PTP','CPT','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'DUPLICADO DE CARNE PTP','DPT','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'DUPLICADO DE TAM','DTA','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'TRASLADO DE SELLO DE INGRESO A DOC.DE VIAJE NUEVO','TSI','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'DEVOLUCIÓN DE PAGO DE TASAS','DVT','D')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ACTUALIZACIÓN DE DATOS EXTRANJERO EN LINEA','ADE','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'SUSPENSIÓN DE PASAPORTES','SUP','P')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'PRORROGA VISA MRE','PMR','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'OFICIO MIGRATORIO PERSONALIZADO','OMP','U')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'SUBSANACION','SUB','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ENTREGA DE CARNÉ DE EXTRANJERÍA','ECE','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ENTREGA DE CARNÉ DE PTP','ETP','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'ENTREGA DE PASAPORTE','EPA','I')
INSERT INTO SidtefimTipoTramite(bActivo, sDescripcion, sSigla, sTipo) VALUES(1,'VULNERABLE','VUL','U')

/*
	► INSERT: SidtefimEtapa
	► SELECT * FROM SidtefimEtapa */
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('<NO DEFINIDO>',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('REVISION DE DOCUMENTOS',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('REGISTRO DE DATOS',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('TOMA DE IMAGENES',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('PRE IMPRESION',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('IMPRESION',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('CONTROL DE CALIDAD',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA DIRECTOR PASAPORTES',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ENTREGA DE PASAPORTE',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('MESA DE PARTES',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('RECEPCIÓN DINM',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ASOCIACION BENEFICIARIO',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('INTERPOL',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ACTUALIZAR DATOS BENEFICIARIO',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('AUTORIZAR IMPRESION',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA SELLO DIR. INMIGRACION',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ENTREGA DE CARNET EXTRANJERIA',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('CONFORMIDAD SUB-DIREC.INMGRA.',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('CONFORMIDAD DIREC.INMGRACION.',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('PAGOS, FECHA Y NRO RD.',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('REGISTRO DE PRORROGA',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('CONFORMIDAD UCI',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ENVIAR A ARCHIVO INMIGRACION',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('MODIFICACION DATOS RCE',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('REGISTRO BENEFICIARIO/GARANTE',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FECHA Y NUMERO DE RD',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FECHA Y NRO. DE OFICIO RR.EE.',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('REGISTRO Y ELABOR. OFICIO',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FECHA Y NRO. DE OFICIO',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('RECEPCION EMBAJADA',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('RECEPCIÓN DNAC',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('EVALUACION DIRECTOR',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('EVALUACION SUB-DIRECTOR',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('INSCRIPCION',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA DIR. NACIONALIZACION',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('APROBACION DE REGISTRO',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ENTREGA DE TITULO',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA DIRECTOR GENERAL',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('RECEPCION DE TITULO',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('RESOLUCIÓN',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('EVALUACIÓN',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA DE MINISTRO',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA SUB DIR. NACIONALIZACION',1)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('RECTIFICACIÓN DE DATOS',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ELABORACIÓN DE RD',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('RECEPCIÓN DE RD',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ELABORACIÓN DE ACTA',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA SUB DIR. PARENTESCO',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('INFORME DE SUB DIRECCIÓN',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('DICTAMEN',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('VISACIÓN DE RESOLUCIÓN',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('VISACIÓN DE SUB-DIRECTOR',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA RESOLUCIÓN - DIRECTOR',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA RESOLUCIÓN - MINISTRO',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('REVISIÓN',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('FIRMA RESOLUCIÓN - PRESIDENTE',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ADJUDICADOR DE PERITOS',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ENTREGA DE CARNÉ P.T.P.',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('CONFORMIDAD Y ENTREGA',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('CONFORMIDAD SUB-GER-MOV.MIGRAT',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('EMISIÓN Y ENTREGA',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('RECONSIDERACION.',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('APELACION.',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('NULIDAD DE OFICIO.',0)
INSERT INTO SidtefimEtapa(sDescripcion, bActivo) VALUES('ACTUALIZACION DE RESIDENCIA',0)

/*
	► INSERT: SidtefimUsuario
	► SELECT * FROM SidtefimUsuario */
INSERT 
	INTO SidtefimUsuario
		(sLogin, sCodigoArea, sDni, sNombre, xPassword, sIdDependencia)
	VALUES
		(
			'rguevarav', '25', '46392613', 'Cristopher Guevara Villegas', '123', '25'
		)

SELECT * FROM SidtefimUsuario
SELECT * FROM SidtefimProcNac
SELECT * FROM SidtefimEtapaProcNac